### ISSUE TITLE
Invisible entities

### ISSUE THREAD

**Issue by LoneDev6** [Esmorall/EntityTrackerFixer#10]
Sometimes entities become invisible and reappear only after server restart

**Comment by redbau** [comment]
This is still happening on my sever as well, although doesn't seem to matter if just after a reboot or not, players are complaining about invisible ghosts, creepers and a few other dangerous mobs like that.

**Comment by rayanbzd** [comment]
Can u post your config ?

**Comment by Elecast2** [comment]
Does it happen with latest version of etf?

**Comment by LoneDev6** [comment]
I don't think so, I didn't get any report since months ago, we can close this
