### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by ArtelGG** [Esmorall/EntityTrackerFixer#2]
**Suggestion List:**
- [ ] Add a reload command which reloads all settings and reloads all of the tasks.
- [ ] Don't send a message to console if the amount of entities was 0.
- [ ] Improve the overall English located within the configuration files' comments, as of right now, they're hardly understandable.

**Comment by ArtelGG** [comment]
**Update:** All of these suggestions have been implemented in [my fork of this project](https://github.com/ArtelGG/EntityTrackerFixer).

**Comment by Elecast2** [comment]
Thanks for the suggestions will be added on next update, and also i will put thanks to ArtelGG on config.yml to improve the english messages
