### ISSUE TITLE
1.16.4 R3 not working

### ISSUE THREAD

**Issue by dotI0** [Esmorall/EntityTrackerFixer#22]
Plugin is not loading on 1.16.4 R3 Spigot
https://pastebin.com/Thvxhrhx

**Comment by cascaseno** [comment]
While Esmorall does not officially update the plugin, here is an unofficial updated version (but that works perfectly) that I've made of the plugin.

GitHub release page: https://github.com/cascaseno/EntityTrackerFixer/releases/1.3.3
Direct plugin download: https://unserversinley.net/misc/jars/EntityTrackerFixer-1.16.4.jar

Have a nice day ^^

**Comment by mrfloris** [comment]
SpigotMC now has a release for version 1.16.4 support.
