### ISSUE TITLE
Build Instructions/Script?

### ISSUE THREAD

**Issue by ROTARTSI82** [Esmorall/EntityTrackerFixer#3]
I've noticed that there is no build script, nor is there a README. Can you please provide us with a way to build this plugin? 

(I know that a precompiled version can be downloaded at [spigot](https://www.spigotmc.org/resources/entitytrackerfixer-fix-1-14-4-entitytick-lag.70902/), but I want to be able to build it from the source.

**Comment by ArtelGG** [comment]
Use an IDE.

**Comment by Elecast2** [comment]
This is small plugin so i don't think i will add build script or something like maven/gradle, but you can add spigot 1.14 1.15 and 1.16 to dependencies and just compile using some ide
