### ISSUE TITLE
Ender Dragon

### ISSUE THREAD

**Issue by x1p** [Esmorall/EntityTrackerFixer#7]
I enabled the experimental function
When summoning the ender_dragon, I suddenly see 2 ender dragons, one of which I can't kill using a tool.
Is it possible this has anything to do with the experimental function? Although it didn't run, so no entities where untracked, I suspect that it has something to do with EntityTrackerFixer.

I removed the End from the world config but it happened again.
Then I completely turned off EntityTrackerFixer and it did not happen

EntityTrackerFixer 1.2.1
Paper 1.14.4

**Comment by Elecast2** [comment]
Will be fixed on the next update, thanks for the report

**Comment by Elecast2** [comment]
If the error still persist try latest update!
